# Generated by Django 4.2.20 on 2025-04-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDSApp', '0003_alter_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ddsrecord',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ddsrecord',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
