# Generated by Django 4.2.20 on 2025-04-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDSApp', '0004_remove_ddsrecord_updated_at_ddsrecord_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ddsrecord',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='ddsrecord',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
